spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/agriotes_cda
    username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB 
        
    
